#name = "Tom"
#description = ""
#keywords = ""
#image = ""
theme = "dark"
primary_color = "#d81b60"
text_align = "center"
#gtag_id = "G-33WB8LVHR6"
base_url = "https://mr8tom.github.io/"

[[sections]]
direction = "row"
item_style = "filled"
[[sections.items]]
title = "s"
url = "https://stream.8tom.de/web/#/tv.html?topParentId=43cfe12fe7d9d8d21251e0964e0232e2&collectionType=tvshows"
[[sections.items]]
title = "l"
url = "https://link.8tom.de/de/collections/36"
[[sections.items]]
title = "a"
url = "https://audio.8tom.de/audiobookshelf/library/c3d39639-835c-4d3a-8904-aa7953684608/bookshelf?filter=genres.8J%252BMtu%252B4jw%253D%253D&sort=mtimeMs&desc=1"
[[sections.items]]
title = "p"
url = "https://pad.8tom.de/lucatom"
[[sections.items]]
title = "h"
url = "https://home.8tom.de"

[[sections]]
direction = "row"
item_style = "filled"
[[sections.items]]
title = "wre"
url = "https://wire.8tom.de/"
[[sections.items]]
title = "tec"
url = "https://tec.8tom.de/"
[[sections.items]]
title = "prn"
url = "https://p.8tom.de/scenes?sortby=date"
[[sections.items]]
title = "wtc"
url = "https://watcharr.8tom.de/"
[[sections.items]]
title = "scr"
url = "https://screen.8tom.de/?room=sonnesaftigsark/"
[[sections.items]]
title = "con"
url = "https://con.8tom.de/"
[[sections.items]]
title = "rss"
url = "https://rss.8tom.de/"
[[sections.items]]
title = "pic"
url = "https://pic.8tom.de/"

[[sections]]
direction = "row"
item_style = "outline"
[[sections.items]]
title = "/"
url = "https://8tom.de/apps/files/"
[[sections.items]]
title = "AZE"
url = "https://8tom.de/apps/files/files/1557730?dir=/Archiv/Arbeit&openfile=true"
[[sections.items]]
title = "FND"
url = "https://8tom.de/apps/thesearchpage/?terms=Shimano&provider=collectives&provider=collectives-pages&provider=collectives-page-content&provider=notes&provider=files&provider=tasks"
[[sections.items]]
title = "DO"
url = "https://8tom.de/apps/tasks/#/calendars/migrated-1"
[[sections.items]]
title = "NOTE"
url = "https://8tom.de/apps/notes"
[[sections.items]]
title = "CAL"
url = "https://8tom.de/apps/calendar/dayGridMonth/now"
[[sections.items]]
title = "COL"
url = "https://8tom.de/apps/collectives/"
[[sections.items]]
title = "PIC"
url = "https://8tom.de/apps/memories/"

[[sections]]
direction = "row"
item_style = "filled"
[[sections.items]]
title = "prx"
url = "https://192.168.2.4:8006/"
[[sections.items]]
title = "frb"
url = "http://192.168.2.1/"
[[sections.items]]
title = "frt"
url = "http://192.168.2.2/"
[[sections.items]]
title = "rpt"
url = "http://192.168.2.3/"
[[sections.items]]
title = "npm"
url = "https://192.168.2.7:81/"
[[sections.items]]
title = "tmx"
url = "http://192.168.2.18/"
[[sections.items]]
title = "lms"
url = "http://192.168.2.11:9000/material/"
[[sections.items]]
title = "wz"
url = "http://192.168.2.42/cgi-bin/main.cgi"
[[sections.items]]
title = "sz"
url = "http://192.168.2.41/cgi-bin/main.cgi"
[[sections.items]]
title = "kü"
url = "http://192.168.2.43/cgi-bin/main.cgi"
[[sections.items]]
title = "ha"
url = "http://192.168.2.6:8123/lovelace/0"
[[sections.items]]
title = "z2m"
url = "http://192.168.2.12:8080/#/"
[[sections.items]]
title = "pi"
url = "http://192.168.2.9/admin/"
[[sections.items]]
title = "stb"
url = "http://192.168.2.44/"
[[sections.items]]
title = "dge"
url = "http://192.168.2.26:5001/"
[[sections.items]]
title = "jdl"
url = "http://192.168.2.26:5800/"
[[sections.items]]
title = "fil"
url = "http://192.168.2.4:8080/files/RootFS/mnt/pool/video/"
[[sections.items]]
title = "arg"
url = "http://192.168.2.21:8080/"

[[sections]]
direction = "row"
item_style = "outline"
[[sections.items]]
title = "thek"
url = "https://mediathekviewweb.de/#query=!ARTE.DE&page=1"
[[sections.items]]
title = "arte"
url = "https://www.arte.tv/de/videos/meistgesehen/"
[[sections.items]]
title = "g"
url = "https://github.com/mr8tom/mr8tom.github.io/blob/main/data.toml"
[[sections.items]]
title = "w"
url = "https://www.timeanddate.de/wetter/deutschland/leipzig/stunden"
[[sections.items]]
title = "y"
url = "https://finance.yahoo.com/portfolio/p_0/view/view_0"
[[sections.items]]
title = "nc"
url = "http://192.168.2.6/"
[[sections.items]]
title = "str"
url = "http://192.168.2.13:8096/"
[[sections.items]]
title = "bk"
url = "http://192.168.2.29/"
[[sections.items]]
title = "mon"
url = "http://192.168.2.19/"
[[sections.items]]
title = "yno"
url = "http://192.168.2.25/"
[[sections.items]]
title = "pdf"
url = "http://192.168.2.18:8080/"
[[sections.items]]
title = "plt"
url = "https://plant.8tom.de/"
[[sections.items]]
title = "rei"
url = "https://reise.8tom.de/"
[[sections.items]]
title = "kch"
url = "https://koch.8tom.de/"
[[sections.items]]
title = "bar"
url = "https://bar.8tom.de/"

[[sections]]
title = "Radio"
description = ""
direction = "row"
item_style = "outline"
[[sections.items]]
title = "DLF"
stream = "https://st01.sslstream.dlf.de/dlf/01/mid/aac/stream.aac"
[[sections.items]]
title = "DLFK"
stream = "https://st02.sslstream.dlf.de/dlf/02/mid/aac/stream.aac"
[[sections.items]]
title = "RP"
stream = "https://stream.radioparadise.com/aac-32"
[[sections.items]]
title = "FLX"
stream = "https://streams.fluxfm.de/chillout/aac-64/audio/"
[[sections.items]]
title = "SOM"
stream = "http://ice1.somafm.com/dronezone-128-aac"
[[sections.items]]
title = "SPC"
stream = "https://ice3.somafm.com/spacestation-128-aac"
[[sections.items]]
title = "SEE"
stream = "https://seasaltradio.stream.laut.fm/seasaltradio"

[[sections.items]]
title = "⏹ Radio Stoppen"
description = '''<div style="text-align: center; padding: 20px;">
  <button id="radioStop" style="padding: 15px 30px; background: #00897b; color: white; border: none; border-radius: 50px; font-size: 18px; cursor: pointer; width: 90%; max-width: 300px;"
          onclick="stopRadio()">Radio Stoppen</button>
</div>
<script>
function stopRadio() {
  let audio = document.getElementById('radioStream') || document.querySelector('audio');
  if (audio) {
    audio.pause();
    audio.currentTime = 0;
    event.target.textContent = 'Gestoppt ✅';
    event.target.style.background = '#f44336';
  } else {
    alert('Kein Radio-Stream gefunden');
  }
}
</script>'''

